### ISSUE TITLE
Update docs with v2.2 core changes

### ISSUE THREAD

**Issue by smol-ninja** [sablier-labs/docs#133]
In preparation for v2.2, docs should be updated with the following new information regarding changes with the core contracts.

### [Overview](https://docs.sablier.com/contracts/v2/reference/overview)
- [x] Add LockupTranched and remove Comptroller

### [Diagrams](https://docs.sablier.com/contracts/v2/reference/diagrams)
- [x] Add lockup tranched section

### Create a Stream
- [x] Review Lockup Linear and Lockup Dynamic
- [x] Add Lockup Tranched

### Stream management
- [x] Update [withdraw from stream section](https://docs.sablier.com/contracts/v2/guides/stream-management/withdraw) with new changes

### [Hooks](https://docs.sablier.com/contracts/v2/guides/hooks)
- [x] Update functions name of recipient hook
- [x] Add a new section  about sender hook

### Miscellaneous
- [x] Review [Etherscan](https://docs.sablier.com/contracts/v2/guides/etherscan)
- [x] Review [snapshot strategies](https://docs.sablier.com/contracts/v2/guides/snapshot-voting)

## Concepts
- [x] New section on LockupTranched under [type of streams](https://docs.sablier.com/concepts/protocol/stream-types)
- [x] Add a new page about Tranches or combine it into [Segments](https://docs.sablier.com/concepts/protocol/segments)
- [x] Remove protocol fees from [Fees](https://docs.sablier.com/concepts/protocol/fees)
- [x] Remove [Governance](https://docs.sablier.com/concepts/governance) entirely
- [x] Update [Glossary](https://docs.sablier.com/concepts/glossary)

**Comment by PaulRBerg** [comment]
beautiful

**Comment by andreivladbrg** [comment]
Very nice organized Shub 

Small note: we will need to update the [diagrams](https://docs.sablier.com/contracts/v2/reference/diagrams), and may use other tools(like [diagrams.net](https://app.diagrams.net/)) instead of `mermaid.js`, how we did in [airstream concept page](https://docs.sablier.com/concepts/protocol/airstreams#diagram)

**Comment by PaulRBerg** [comment]
What's wrong with Mermaid? It's pretty cool to keep the diagrams in version control.

**Comment by andreivladbrg** [comment]
> What's wrong with Mermaid?

the problem with mermaid is that it's super limited in how you can customize them

> It's pretty cool to keep the diagrams in version control

yeah, they are very useful. i haven't said to remove them, but to **update** them according to the **new** storage layout:
- `Lockup` -> common storage
- `LockupLinear` -> cliffs
- `LockupDynamic` -> segments
- `LockupTranched` -> tranches

i doubt that mermaid will have the bandwidth to represent these accurately and beautifully

**Comment by PaulRBerg** [comment]
> the problem with mermaid is that it's super limited in how you can customize them
> ...
> i doubt that mermaid will have the bandwidth to represent these accurately and beautifully

Fair

**Comment by andreivladbrg** [comment]
Leaving this here, maybe it would be helpful: 

![diverse1 drawio](https://github.com/sablier-labs/docs/assets/99738872/60f07b2a-97d6-41aa-b6d0-8a994bf38314)
