### ISSUE TITLE
Update docs with v2.2 periphery changes

### ISSUE THREAD

**Issue by smol-ninja** [sablier-labs/docs#134]
Similar to https://github.com/sablier-labs/docs/issues/133, docs should be updated with the following new information regarding changes with the periphery contracts.

### [Overview](https://docs.sablier.com/contracts/v2/reference/overview)
- [x] Rename MerkleStreamer to MerkleLockup

## Guides
- [x] Add Batch Tranched Streams in [Batch Create Streams section](https://docs.sablier.com/contracts/v2/guides/batch-create-streams/batch-linear-streams)
- [x] Create a new guide on how to create an airstream campaign using MerkleLockup 

## Concepts
- [x] Update [Glossary](https://docs.sablier.com/concepts/glossary)
